/* mne65ud32NewInstructions.h — generated from source/instructionDefs.v */

/* ------------------------------------------------------------------ LDA */
{ NULL, v_mnemonic, "lda",    0, AF_L_FROM_WORDADR, { 0xb3  } },
{ NULL, v_mnemonic, "lda",    0, AF_W_FROM_WORDADR, { 0x13  } },
{ NULL, v_mnemonic, "ldua",   0, AF_W_FROM_WORDADR, { 0x213 } },
{ NULL, v_mnemonic, "lda",    0, AF_IMM32,          { 0x43  } },
{ NULL, v_mnemonic, "lda",    0, AF_IMM16,          { 0x33  } },
{ NULL, v_mnemonic, "ldua",   0, AF_IMM16,          { 0x233 } },
{ NULL, v_mnemonic, "lda",    0, AF_REGXL,          { 0xf7  } },
{ NULL, v_mnemonic, "lda",    0, AF_REGUXL,         { 0x2f7 } },
{ NULL, v_mnemonic, "lda",    0, AF_REGXW,          { 0xd7  } },
{ NULL, v_mnemonic, "lda",    0, AF_REGUXW,         { 0x2d7 } },
{ NULL, v_mnemonic, "lda",    0, AF_REGXB,          { 0xe7  } },
{ NULL, v_mnemonic, "lda",    0, AF_REGUXB,         { 0x2e7 } },
{ NULL, v_mnemonic, "lda",    0, AF_REGYL,          { 0xaf  } },
{ NULL, v_mnemonic, "lda",    0, AF_REGUYL,         { 0x2af } },
{ NULL, v_mnemonic, "lda",    0, AF_REGYW,          { 0xdf  } },
{ NULL, v_mnemonic, "lda",    0, AF_REGUYW,         { 0x2df } },
{ NULL, v_mnemonic, "lda",    0, AF_REGYB,          { 0xdc  } },
{ NULL, v_mnemonic, "lda",    0, AF_REGUYB,         { 0x2dc } },

/* ------------------------------------------------------------------ LDX */
{ NULL, v_mnemonic, "ldx",    0, AF_L_FROM_WORDADR, { 0x9f  } },
{ NULL, v_mnemonic, "ldx",    0, AF_W_FROM_WORDADR, { 0x1f  } },
{ NULL, v_mnemonic, "ldux",   0, AF_W_FROM_WORDADR, { 0x21f } },
{ NULL, v_mnemonic, "ldx",    0, AF_IMM32,          { 0x5f  } },
{ NULL, v_mnemonic, "ldx",    0, AF_IMM16,          { 0x4f  } },
{ NULL, v_mnemonic, "ldux",   0, AF_IMM16,          { 0x24f } },
{ NULL, v_mnemonic, "ldx",    0, AF_REGYL,          { 0xf3  } },
{ NULL, v_mnemonic, "ldx",    0, AF_REGUYL,         { 0x2f3 } },
{ NULL, v_mnemonic, "ldx",    0, AF_REGYW,          { 0xfc  } },
{ NULL, v_mnemonic, "ldx",    0, AF_REGUYW,         { 0x2fc } },
{ NULL, v_mnemonic, "ldx",    0, AF_REGYB,          { 0x2fd } },
{ NULL, v_mnemonic, "ldx",    0, AF_REGUYB,         { 0x2fe } },

/* ------------------------------------------------------------------ LDY */
{ NULL, v_mnemonic, "ldy",    0, AF_L_FROM_WORDADR, { 0x37  } },
{ NULL, v_mnemonic, "ldy",    0, AF_W_FROM_WORDADR, { 0xbf  } },
{ NULL, v_mnemonic, "lduy",   0, AF_W_FROM_WORDADR, { 0x2bf } },
{ NULL, v_mnemonic, "ldy",    0, AF_IMM32,          { 0xff  } },
{ NULL, v_mnemonic, "ldy",    0, AF_IMM16,          { 0xef  } },
{ NULL, v_mnemonic, "lduy",   0, AF_IMM16,          { 0x2ef } },

/* ------------------------------------------------------------------ STA */
{ NULL, v_mnemonic, "sta",    0, AF_L_FROM_WORDADR, { 0xa3  } },
{ NULL, v_mnemonic, "sta",    0, AF_W_FROM_WORDADR, { 0xc3  } },
{ NULL, v_mnemonic, "stua",   0, AF_W_FROM_WORDADR, { 0x2c3 } },
{ NULL, v_mnemonic, "sta",    0, AF_REGXL,          { 0x47  } },
{ NULL, v_mnemonic, "sta",    0, AF_REGUXL,         { 0x247 } },
{ NULL, v_mnemonic, "sta",    0, AF_REGXW,          { 0xa7  } },
{ NULL, v_mnemonic, "sta",    0, AF_REGUXW,         { 0x2a7 } },
{ NULL, v_mnemonic, "sta",    0, AF_REGYL,          { 0x57  } },
{ NULL, v_mnemonic, "sta",    0, AF_REGUYL,         { 0x257 } },
{ NULL, v_mnemonic, "sta",    0, AF_REGYW,          { 0xb7  } },
{ NULL, v_mnemonic, "sta",    0, AF_REGUYW,         { 0x2b7 } },
{ NULL, v_mnemonic, "sta",    0, AF_REGXB,          { 0x2a0 } },
{ NULL, v_mnemonic, "sta",    0, AF_REGUXB,         { 0x2b0 } },
{ NULL, v_mnemonic, "sta",    0, AF_REGYB,          { 0x2c0 } },
{ NULL, v_mnemonic, "sta",    0, AF_REGUYB,         { 0x2d0 } },

/* ------------------------------------------------------------------ STX */
{ NULL, v_mnemonic, "stx",    0, AF_L_FROM_WORDADR, { 0x8f  } },
{ NULL, v_mnemonic, "stx",    0, AF_W_FROM_WORDADR, { 0x2f  } },
{ NULL, v_mnemonic, "stux",   0, AF_W_FROM_WORDADR, { 0x22f } },
{ NULL, v_mnemonic, "stx",    0, AF_REGYL,          { 0x67  } },
{ NULL, v_mnemonic, "stx",    0, AF_REGUYL,         { 0x267 } },
{ NULL, v_mnemonic, "stx",    0, AF_REGYW,          { 0xc7  } },
{ NULL, v_mnemonic, "stx",    0, AF_REGUYW,         { 0x2c7 } },
{ NULL, v_mnemonic, "stx",    0, AF_REGYB,          { 0x2e0 } },
{ NULL, v_mnemonic, "stx",    0, AF_REGUYB,         { 0x2f0 } },

/* ------------------------------------------------------------------ STY */
{ NULL, v_mnemonic, "sty",    0, AF_L_FROM_WORDADR, { 0x27  } },
{ NULL, v_mnemonic, "sty",    0, AF_W_FROM_WORDADR, { 0xcf  } },
{ NULL, v_mnemonic, "stuy",   0, AF_W_FROM_WORDADR, { 0x2cf } },
{ NULL, v_mnemonic, "sty",    0, AF_REGXB,          { 0x211 } },
{ NULL, v_mnemonic, "sty",    0, AF_REGUXB,         { 0x221 } },

/* ------------------------------------------------------------------ CPA */
{ NULL, v_mnemonic, "cpa",    0, AF_L_FROM_WORDADR, { 0x0b  } },
{ NULL, v_mnemonic, "cpa",    0, AF_W_FROM_WORDADR, { 0x1b  } },
{ NULL, v_mnemonic, "cpua",   0, AF_W_FROM_WORDADR, { 0x21b } },
{ NULL, v_mnemonic, "cpa",    0, AF_IMM32,          { 0x2b  } },
{ NULL, v_mnemonic, "cpa",    0, AF_IMM16,          { 0x3b  } },
{ NULL, v_mnemonic, "cpua",   0, AF_IMM16,          { 0x23b } },

/* ------------------------------------------------------------------ CPX */
{ NULL, v_mnemonic, "cpx",    0, AF_L_FROM_WORDADR, { 0x4b  } },
{ NULL, v_mnemonic, "cpx",    0, AF_W_FROM_WORDADR, { 0x5b  } },
{ NULL, v_mnemonic, "cpux",   0, AF_W_FROM_WORDADR, { 0x25b } },
{ NULL, v_mnemonic, "cpx",    0, AF_IMM32,          { 0x6b  } },
{ NULL, v_mnemonic, "cpx",    0, AF_IMM16,          { 0x7b  } },
{ NULL, v_mnemonic, "cpux",   0, AF_IMM16,          { 0x27b } },

/* ------------------------------------------------------------------ CPY */
{ NULL, v_mnemonic, "cpy",    0, AF_L_FROM_WORDADR, { 0x8b  } },
{ NULL, v_mnemonic, "cpy",    0, AF_W_FROM_WORDADR, { 0x9b  } },
{ NULL, v_mnemonic, "cpuy",   0, AF_W_FROM_WORDADR, { 0x29b } },
{ NULL, v_mnemonic, "cpy",    0, AF_IMM32,          { 0xab  } },
{ NULL, v_mnemonic, "cpy",    0, AF_IMM16,          { 0xbb  } },
{ NULL, v_mnemonic, "cpuy",   0, AF_IMM16,          { 0x2bb } },

/* ------------------------------------------------------------------ ADC (ADA + SBA) */
{ NULL, v_mnemonic, "ada",    0, AF_IMM32,          { 0xcb  } },
{ NULL, v_mnemonic, "ada",    0, AF_IMM16,          { 0xdb  } },
{ NULL, v_mnemonic, "adua",   0, AF_IMM16,          { 0x2db } },
{ NULL, v_mnemonic, "ada",    0, AF_L_FROM_WORDADR, { 0xeb  } },
{ NULL, v_mnemonic, "ada",    0, AF_W_FROM_WORDADR, { 0xfb  } },
{ NULL, v_mnemonic, "adua",   0, AF_W_FROM_WORDADR, { 0x2fb } },
{ NULL, v_mnemonic, "sba",    0, AF_IMM32,          { 0x2cb } },
{ NULL, v_mnemonic, "sba",    0, AF_IMM16,          { 0x22  } },
{ NULL, v_mnemonic, "sbua",   0, AF_IMM16,          { 0x222 } },
{ NULL, v_mnemonic, "sba",    0, AF_L_FROM_WORDADR, { 0x2eb } },
{ NULL, v_mnemonic, "sba",    0, AF_W_FROM_WORDADR, { 0x42  } },
{ NULL, v_mnemonic, "sbua",   0, AF_W_FROM_WORDADR, { 0x242 } },

/* ------------------------------------------------------------------ ADXC (ADX + SBX) */
{ NULL, v_mnemonic, "adx",    0, AF_IMM32,          { 0x04  } },
{ NULL, v_mnemonic, "adx",    0, AF_IMM16,          { 0x14  } },
{ NULL, v_mnemonic, "adux",   0, AF_IMM16,          { 0x214 } },
{ NULL, v_mnemonic, "adx",    0, AF_L_FROM_WORDADR, { 0x44  } },
{ NULL, v_mnemonic, "adx",    0, AF_W_FROM_WORDADR, { 0x54  } },
{ NULL, v_mnemonic, "adux",   0, AF_W_FROM_WORDADR, { 0x254 } },
{ NULL, v_mnemonic, "sbx",    0, AF_IMM32,          { 0x204 } },
{ NULL, v_mnemonic, "sbx",    0, AF_IMM16,          { 0x62  } },
{ NULL, v_mnemonic, "sbux",   0, AF_IMM16,          { 0x262 } },
{ NULL, v_mnemonic, "sbx",    0, AF_L_FROM_WORDADR, { 0x244 } },
{ NULL, v_mnemonic, "sbx",    0, AF_W_FROM_WORDADR, { 0x82  } },
{ NULL, v_mnemonic, "sbux",   0, AF_W_FROM_WORDADR, { 0x282 } },

/* ------------------------------------------------------------------ ADY (ADY + SBY) */
{ NULL, v_mnemonic, "ady",    0, AF_IMM32,          { 0x64  } },
{ NULL, v_mnemonic, "ady",    0, AF_IMM16,          { 0x74  } },
{ NULL, v_mnemonic, "aduy",   0, AF_IMM16,          { 0x274 } },
{ NULL, v_mnemonic, "ady",    0, AF_L_FROM_WORDADR, { 0xd4  } },
{ NULL, v_mnemonic, "ady",    0, AF_W_FROM_WORDADR, { 0xf4  } },
{ NULL, v_mnemonic, "aduy",   0, AF_W_FROM_WORDADR, { 0x2f4 } },
{ NULL, v_mnemonic, "sby",    0, AF_IMM32,          { 0x264 } },
{ NULL, v_mnemonic, "sby",    0, AF_IMM16,          { 0xc2  } },
{ NULL, v_mnemonic, "sbuy",   0, AF_IMM16,          { 0x2c2 } },
{ NULL, v_mnemonic, "sby",    0, AF_L_FROM_WORDADR, { 0x2d4 } },
{ NULL, v_mnemonic, "sby",    0, AF_W_FROM_WORDADR, { 0xe2  } },
{ NULL, v_mnemonic, "sbuy",   0, AF_W_FROM_WORDADR, { 0x2e2 } },

/* ------------------------------------------------------------------ Transfer */
{ NULL, v_mnemonic, "tax",    0, AF_IMP_L,          { 0x200 } },
{ NULL, v_mnemonic, "tay",    0, AF_IMP_L,          { 0x201 } },
{ NULL, v_mnemonic, "txa",    0, AF_IMP_L,          { 0x205 } },
{ NULL, v_mnemonic, "tya",    0, AF_IMP_L,          { 0x206 } },

/* ------------------------------------------------------------------ Logic (AND / ORA / EOR) */
{ NULL, v_mnemonic, "and",    0, AF_IMM32,          { 0x53  } },
{ NULL, v_mnemonic, "and",    0, AF_IMM16,          { 0x253 } },
{ NULL, v_mnemonic, "andu",   0, AF_IMM16,          { 0x263 } },
{ NULL, v_mnemonic, "and",    0, AF_L_FROM_WORDADR, { 0x2a3 } },
{ NULL, v_mnemonic, "and",    0, AF_W_FROM_WORDADR, { 0x2b3 } },
{ NULL, v_mnemonic, "andu",   0, AF_W_FROM_WORDADR, { 0x2d3 } },
{ NULL, v_mnemonic, "ora",    0, AF_IMM32,          { 0x63  } },
{ NULL, v_mnemonic, "ora",    0, AF_IMM16,          { 0x209 } },
{ NULL, v_mnemonic, "orua",   0, AF_IMM16,          { 0x219 } },
{ NULL, v_mnemonic, "ora",    0, AF_L_FROM_WORDADR, { 0x229 } },
{ NULL, v_mnemonic, "ora",    0, AF_W_FROM_WORDADR, { 0x239 } },
{ NULL, v_mnemonic, "orua",   0, AF_W_FROM_WORDADR, { 0x249 } },
{ NULL, v_mnemonic, "eor",    0, AF_IMM32,          { 0x73  } },
{ NULL, v_mnemonic, "eor",    0, AF_IMM16,          { 0x259 } },
{ NULL, v_mnemonic, "eoru",   0, AF_IMM16,          { 0x269 } },
{ NULL, v_mnemonic, "eor",    0, AF_L_FROM_WORDADR, { 0x279 } },
{ NULL, v_mnemonic, "eor",    0, AF_W_FROM_WORDADR, { 0x289 } },
{ NULL, v_mnemonic, "eoru",   0, AF_W_FROM_WORDADR, { 0x299 } },

/* ------------------------------------------------------------------ Inc-Dec */
{ NULL, v_mnemonic, "deca",   0, AF_IMP_L,          { 0x83  } },
{ NULL, v_mnemonic, "inca",   0, AF_IMP_L,          { 0x93  } },
{ NULL, v_mnemonic, "decx",   0, AF_IMP_L,          { 0x6f  } },
{ NULL, v_mnemonic, "incx",   0, AF_IMP_L,          { 0x7f  } },
{ NULL, v_mnemonic, "decy",   0, AF_IMP_L,          { 0x07  } },
{ NULL, v_mnemonic, "incy",   0, AF_IMP_L,          { 0x17  } },
{ NULL, v_mnemonic, "deca",   0, AF_IMP_W,          { 0x2ce } },
{ NULL, v_mnemonic, "inca",   0, AF_IMP_W,          { 0x26e } },
{ NULL, v_mnemonic, "decua",  0, AF_IMP_W,          { 0x23e } },
{ NULL, v_mnemonic, "incua",  0, AF_IMP_W,          { 0x29e } },
{ NULL, v_mnemonic, "decx",   0, AF_IMP_W,          { 0x2ee } },
{ NULL, v_mnemonic, "incx",   0, AF_IMP_W,          { 0x28e } },
{ NULL, v_mnemonic, "decux",  0, AF_IMP_W,          { 0x25e } },
{ NULL, v_mnemonic, "incux",  0, AF_IMP_W,          { 0x2be } },
{ NULL, v_mnemonic, "decy",   0, AF_IMP_W,          { 0x2de } },
{ NULL, v_mnemonic, "incy",   0, AF_IMP_W,          { 0x27e } },
{ NULL, v_mnemonic, "decuy",  0, AF_IMP_W,          { 0x24e } },
{ NULL, v_mnemonic, "incuy",  0, AF_IMP_W,          { 0x2ae } },

/* ------------------------------------------------------------------ Rotate / Shift / Swap */
{ NULL, v_mnemonic, "sea",    0, AF_IMP_L,          { 0x03  } },
{ NULL, v_mnemonic, "sex",    0, AF_IMP_L,          { 0xd3  } },
{ NULL, v_mnemonic, "sey",    0, AF_IMP_L,          { 0xe3  } },
{ NULL, v_mnemonic, "swapa",  0, AF_IMP_L,          { 0x0c  } },
{ NULL, v_mnemonic, "swapx",  0, AF_IMP_L,          { 0x1c  } },
{ NULL, v_mnemonic, "swapy",  0, AF_IMP_L,          { 0x5c  } },
{ NULL, v_mnemonic, "nega",   0, AF_IMP_L,          { 0x0f  } },
{ NULL, v_mnemonic, "nota",   0, AF_IMP_L,          { 0x20f } },
{ NULL, v_mnemonic, "ror8",   0, AF_IMP_L,          { 0x3f  } },
{ NULL, v_mnemonic, "rol8",   0, AF_IMP_L,          { 0x23f } },
{ NULL, v_mnemonic, "lsr",    0, AF_IMP_L,          { 0x77  } },
{ NULL, v_mnemonic, "lsl",    0, AF_IMP_L,          { 0x277 } },
{ NULL, v_mnemonic, "asr",    0, AF_IMP_L,          { 0x203 } },

/* ------------------------------------------------------------------ Extend */
{ NULL, v_mnemonic, "ext",    0, AF_IMP_L,          { 0x87  } },
{ NULL, v_mnemonic, "ext",    0, AF_IMP_W,          { 0x287 } },
{ NULL, v_mnemonic, "extns",  0, AF_IMP_L,          { 0x20d } },
{ NULL, v_mnemonic, "extns",  0, AF_IMP_W,          { 0x21d } },
{ NULL, v_mnemonic, "extbl",   0, AF_IMP,            { 0x22d } },
{ NULL, v_mnemonic, "extnsbl", 0, AF_IMP,            { 0x23d } },

/* ------------------------------------------------------------------ Multiply / Divide */
{ NULL, v_mnemonic, "mulsfp", 0, AF_IMM32,          { 0x97  } },
{ NULL, v_mnemonic, "mulsfp", 0, AF_REGXL,          { 0x297 } },
{ NULL, v_mnemonic, "mulsfp", 0, AF_L_FROM_WORDADR, { 0x298 } },
{ NULL, v_mnemonic, "muls",   0, AF_IMM16,          { 0x261 } },
{ NULL, v_mnemonic, "muls",   0, AF_REGXW,          { 0x271 } },
{ NULL, v_mnemonic, "muls",   0, AF_W_FROM_WORDADR, { 0x281 } },
{ NULL, v_mnemonic, "divs",   0, AF_IMM32,          { 0x20e } },
{ NULL, v_mnemonic, "divs",   0, AF_REGXL,          { 0x21e } },
{ NULL, v_mnemonic, "divs",   0, AF_L_FROM_WORDADR, { 0x22e } },
{ NULL, v_mnemonic, "divs",   0, AF_IMM16,          { 0x231 } },
{ NULL, v_mnemonic, "divs",   0, AF_REGXW,          { 0x241 } },
{ NULL, v_mnemonic, "divs",   0, AF_W_FROM_WORDADR, { 0x251 } },

/* ------------------------------------------------------------------ Push / Pull */
{ NULL, v_mnemonic, "pha",    0, AF_IMP_L,          { 0x20a } },
{ NULL, v_mnemonic, "pla",    0, AF_IMP_L,          { 0x21a } },
{ NULL, v_mnemonic, "phx",    0, AF_IMP_L,          { 0x22a } },
{ NULL, v_mnemonic, "plx",    0, AF_IMP_L,          { 0x23a } },
{ NULL, v_mnemonic, "phy",    0, AF_IMP_L,          { 0x24a } },
{ NULL, v_mnemonic, "ply",    0, AF_IMP_L,          { 0x25a } },
{ NULL, v_mnemonic, "pha",    0, AF_IMP_W,          { 0x26a } },
{ NULL, v_mnemonic, "pla",    0, AF_IMP_W,          { 0x27a } },
{ NULL, v_mnemonic, "phx",    0, AF_IMP_W,          { 0x28a } },
{ NULL, v_mnemonic, "plx",    0, AF_IMP_W,          { 0x29a } },
{ NULL, v_mnemonic, "phy",    0, AF_IMP_W,          { 0x2aa } },
{ NULL, v_mnemonic, "ply",    0, AF_IMP_W,          { 0x2ba } },
{ NULL, v_mnemonic, "phua",   0, AF_IMP_W,          { 0x2ca } },
{ NULL, v_mnemonic, "plua",   0, AF_IMP_W,          { 0x2da } },
{ NULL, v_mnemonic, "phux",   0, AF_IMP_W,          { 0x2ea } },
{ NULL, v_mnemonic, "plux",   0, AF_IMP_W,          { 0x2fa } },
{ NULL, v_mnemonic, "phuy",   0, AF_IMP_W,          { 0x22c } },
{ NULL, v_mnemonic, "pluy",   0, AF_IMP_W,          { 0x23c } },

/* ------------------------------------------------------------------ CLR */
{ NULL, v_mnemonic, "clra",   0, AF_IMP_L,          { 0x210 } },
{ NULL, v_mnemonic, "clra",   0, AF_IMP_W,          { 0x220 } },
{ NULL, v_mnemonic, "clrua",  0, AF_IMP_W,          { 0x230 } },
{ NULL, v_mnemonic, "clrx",   0, AF_IMP_L,          { 0x240 } },
{ NULL, v_mnemonic, "clrx",   0, AF_IMP_W,          { 0x250 } },
{ NULL, v_mnemonic, "clrux",  0, AF_IMP_W,          { 0x260 } },
{ NULL, v_mnemonic, "clry",   0, AF_IMP_L,          { 0x270 } },
{ NULL, v_mnemonic, "clry",   0, AF_IMP_W,          { 0x280 } },
{ NULL, v_mnemonic, "clruy",  0, AF_IMP_W,          { 0x290 } },
